### PR TITLE
add public headers to podspec

### PR DESCRIPTION
**Pull request by auraev**

### CODE REVIEW

**Comment by keith** [comment]
Is there a CocoaPods issue that makes this required? This should be implicit I believe?

**Comment by auraev** [comment]
It's need for console build same gradle Jenkins plugin

понедельник, 30 ноября 2015 г. пользователь Keith Smiley написал:

**Comment by keith** [comment]
This sounds like something that should be fixed on the Jenkins plugin. If you don't specify this key, CocoaPods makes all headers public.

**Comment by auraev** [comment]
Its can break any console build i think (appcode, and etc), but if you dont
want - dont merge

2015-11-30 14:19 GMT-05:00 Keith Smiley notifications@github.com:

**Comment by keith** [comment]
I'm able to build this from the console no problem? The large majority of pods don't specify this and you can definitely build them from the command line. Could there be another factor here?

**Comment by auraev** [comment]
Error looks like :

#import "NSString+MD5.h"

```
    ^
```

<unknown>:0: error: failed to import bridging header
'/Users/jenkins/workspace/project-ios/project/project2/project2-Bridging-Header.h'

2015-11-30 14:24 GMT-05:00 Keith Smiley notifications@github.com:

**Comment by keith** [comment]
Is this still an issue? This shouldn't be a problem unless there is a CP bug. But if it still is I can merge this as it won't take much keeping up with.

**Comment by keith** [comment]
Closing this. Reopen if it's still an issue!

**Pull request closed without merging**
